# _config.yml
title: محمد الجوكر
email: your.email@example.com
description: >-
  موقع شخصي لعرض كورسات البرمجة والتداول.

# إعدادات المجموعات (Collections) للسماح بقراءة محتوى CMS
collections:
  programming_courses:
    output: true # مهمة إذا أردت صفحة لكل كورس (مثل /programming_courses/course-title)
  trading_courses:
    output: true # مهمة إذا أردت صفحة لكل كورس

defaults:
  - scope:
      path: ""
      type: "programming_courses"
    values:
      layout: "default" # يمكنك إنشاء تخطيط خاص بالكورسات هنا
  - scope:
      path: ""
      type: "trading_courses"
    values:
      layout: "default"
      
