backend:
  name: github
  repo: mohamedeljoker-ss7/mohamedeljoker-ss7.github.io
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "programming_courses"
    label: "دورات البرمجة"
    folder: "_programming_courses"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "الوصف", name: "description", widget: "text" }
      - { label: "الصورة", name: "image", widget: "image" }
      - { label: "المحتوى", name: "body", widget: "markdown" }
      
